name: ci

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you split dev deps, also: pip install -r requirements-dev.txt
          pip install ruff pytest

      - name: Lint
        run: ruff check .

      - name: Unit tests
        env:
          API_KEY: "ci_key"   # ensures endpoints guarded by API key are testable if needed
        run: pytest -q
